<?php

use Illuminate\Database\Seeder;

class CreateRetailerContent extends Seeder
{
    const RETAILER_NAMES = [
        "coppertank grill",
        "momo sushi",
        "tacofino",
        "amanzon",
        "west coast liquer store",
        "kins ker",
        "bpi",
        "melville market",
        "the yale saloon",
        "shell",
        "yakiniku chosun",
        "t&t",
        "asa vitis",
        "cobs",
        "fish café",
        "cinemaplex",
        "the secret garden",
        "equitable life",
        "laurance & chico",
        "honolulu",
        "asa sushi",
        "andy - building manager",
        "chipotle",
        "google",
        "artigiano",
        "white spot",
        "tim hortons",
        "london drugs",
        "fido",
        "treloar physio",
        "chewies",
        "gyu-kaku",
        "asa",
        "kerrisdale pharmacy",
        "barn nork",
        "spicy6",
        "superstore",
        "jugo juice",
        "canadian tire",
        "easypark",
        "max's bakery",
        "crepe and cafe",
        "paybyphone",
        "flamingo",
        "dennys",
        "sunrun",
        "mr shawarma",
        "dexcom",
        "squamish valley",
        "zookaz",
        "netflix",
        "blenz",
        "pizza hut",
        "raman",
        "ubc parking",
        "town pentry",
        "save on foods",
        "rice and noodles",
        "the pony",
        "horen",
        "unknown",
        "ferry",
        "subway",
        "marine gateway liquor",
        "manchester pub",
        "freshi",
        "cafe crepe",
        "pink elephant",
        "lilwat gas station",
        "laurence & chico",
        "rbc",
        "breka",
        "lanagara",
        "j&j",
        "mcdonalds",
        "impark",
        "shoppers",
        "rwam",
        "damso",
        "carlos obrayan",
        "whistler dispatch taxi",
        "the dunbar pub",
        "coast",
        "cactus club",
        "jinya",
        "dosa",
        "car2go",
        "the secret garden tea",
        "chongqing",
        "miniso",
        "langara",
        "nero",
        "new india buffet",
        "mec",
        "the dumbar public house",
        "dorit drori",
        "sunlight farm",
        "spotify",
        "earls",
        "sofra",
        "soccer cents",
        "cineplex",
        "shaw",
        "bosleys",
        "jcc",
        "steamship grill",
        "famous player",
        "asa japanese restauran",
        "airbnb",
        "mobil350",
        "amazon",
        "evo",
        "a&w",
        "spicy 6",
        "tenderland meats",
        "guu",
        "starbucks",
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = array_map(function (string $name) {
            return ["name" => $name];
        }, self::RETAILER_NAMES);

        \App\Retailer::insert($names);
    }
}
